### ISSUE TITLE
[쥬라리움 파주] RMS 상품 등록 이슈 

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#13]
RMS 상품 등록 후 포스 상품 선택 시 표시창에 빨간글자로 사진과 같이 상품 표시가 됩니다.
단체-소인(15%할인)
단체-대인(15%할인) 
두가지 상품 등록 하였는데 소인 상품만 색상이 변경 되어 있습니다.
우선 포스 결제 및 닙스 카드 승인 / 결제 매출을 잘 올라 오고 있습니다. 

확인 완료 및 보완 되는 대로 코멘트 부탁 드립니다.

감사합니다.

사진 공유 드립니다.

![KakaoTalk_20191029_141750687](https://user-images.githubusercontent.com/56943833/67744993-66370200-fa66-11e9-90ef-5f76ddbc474c.jpg)

**Comment by KwanJong-Kim-in-TU** [comment]
소스는 수정완료 했습니다
히어로즈와 같은 버젼을 오픈할 예정입니다
포스 프로그램 변경 작업을 언제 진행 할수 있을찌 일정을 잡아주세요
