### ISSUE TITLE
[히어로 키즈파크] pos 영수증 내용 수정 요청

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#14]
히어로 키즈파크 전지점 포스 출력 영수증에 보면 전화번호가 전부 히어로 본사로 연락처가 기입 되어있다고 합니다. 
각시설별 정보 공유 드립니다.  
확인 및 각지점 연락처 및 주소 수정 부탁 드립니다. 

히어로 지점 별 영수증 연락처 수정 요청 
-----------------------------------------------------------------------
■천안점
054-624-1009->**041-903-2233 변경요청**
-----------------------------------------------------------------------
■동탄점
054-624-1009->**031-8043-5279 변경요청**
-----------------------------------------------------------------------
■양산점(zoo포함)
054-624-1009->**055-785-1098 변경요청**
-----------------------------------------------------------------------
■부산명지점
054-624-1009->**051-710-1666 변경요청** 
-----------------------------------------------------------------------
■일산점 
054-624-1009->**031-994-7073 변경요청**
-----------------------------------------------------------------------
■대구점
054-624-1009->**053-719-3773 변경요청**

주소추가
대구광역시 수성구 유니버시이드로 140,1호
->**대구광역시 수성구 유니버시이드로 140, 키테넌트 1호**
-----------------------------------------------------------------------
■고양점 
054-624-1009->**031-818-6333 변경요청**
-----------------------------------------------------------------------

![20191030_153322](https://user-images.githubusercontent.com/56943833/67834617-369dfd80-fb2b-11e9-961a-afd8eadaaa8b.jpg)

**Comment by kimsang5916** [comment]
POS 영수증 내용 수정이 완료 되었는지 회신 부탁 드립니다.

**Comment by KwanJong-Kim-in-TU** [comment]
변경완료 했습니다
포스를 다시 실행하시면 적용됩니다

**Comment by kimsang5916** [comment]
네 매장에 공유 드리겠습니다.
