### ISSUE TITLE
[히어로 전지점] 매출일보 현금/ 현금영수증 이슈 

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#16]
매출일보상 현금 내역들 관련 전지점 체크 부탁 드립니다 
소분류의 현금 내역이 결제별 매출내역 현금에 적용이 안되부분도 있고 
상이 부분도 있습니다. 
11/5 내용정리해서 보내 주신 캡쳐본 전달 드립니다. 
수정 부탁 드립니다. 
감사합니다.

![KakaoTalk_20191106_101619798](https://user-images.githubusercontent.com/56943833/68260352-24b6e000-0080-11ea-8542-7b8d61a112a2.png)

히어로에서 정리해서 보내준 이슈 정리본 

![1234f](https://user-images.githubusercontent.com/56943833/68260366-35ffec80-0080-11ea-90af-7feb7203a383.PNG)

rms 매출일보상 캡쳐본

**Comment by KwanJong-Kim-in-TU** [comment]
사진이 어느지점 건지요?

**Comment by mr-jang** [comment]
11월 5일 전일 시점입니다

**Comment by KwanJong-Kim-in-TU** [comment]
어느 지점인지를 알려달라는건데요..기준을 잡아야 해서

**Comment by mr-jang** [comment]
아 글씨 잘못봤는데 전지점 입니다 본사 담당자가 11월 5일 전지점 내역 확인 및 정리해서 보내준 내용입니다. 그리고 두번째 사진은 명지점만 캡쳐해서 보내드린거에요~!

**Comment by KwanJong-Kim-in-TU** [comment]
전지점 적용했습니다. 18:17분

**Comment by mr-jang** [comment]
감사합니다 확인 해보겠습니다.

**Comment by mr-jang** [comment]
명지지점이랑 동탄지점 보면 사진과 같이 현금 매출이 없는데 건수가 잡혀있습니다 
확인 부탁드립니다.
사진첨부드립니다

![캡처111](https://user-images.githubusercontent.com/56943833/68285746-2f469900-00c3-11ea-8ac4-1e2fc147c33a.PNG)
동탄지점 

![캡처ddds](https://user-images.githubusercontent.com/56943833/68285762-366da700-00c3-11ea-8136-5fc6738184fe.PNG)
명지지점

**Comment by KwanJong-Kim-in-TU** [comment]
건수는 0원짜리 상품도 건수로 잡히게 되어있습니다
