### ISSUE TITLE
[히어로] 프로그램 통합  일정공유 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/PLACEM#18]
하어로 프로그램 통합 일정 

동탄점 
11월 27일 
오전 9시 30분 
프로그램 통합 작업 예정 

천안점 
12월 2일 
오전 9시 00 분 
프로그램 통합 작업 예정 

참고부탁 드립니다.

**Comment by KwanJong-Kim-in-TU** [comment]
27일 천안점 1차 테스트 완료
