### ISSUE TITLE
매출일보(현금)

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/PLACEM#4]
**증상**
신규 개발된 매출 일보 상의 
일반 현금 결제된 금액이 
현금영수증 승인 금의 포함 되는 증상 

확인 완료 및 보완 되는 대로 코멘트 부탁 드립니다.

**Comment by KwanJong-Kim-in-TU** [comment]
현금금에서 현금영수증 금액 제외 함
바로 조회 가능합니다

**Comment by mr-jang** [comment]
내용 전달 및 확인 요청 해보겠습니다.
감사합니다.
