### ISSUE TITLE
수수료 매장 기능 관련 검토 요청 

### ISSUE THREAD

**Issue by kimsang5916** [kimsang5916/PLACEM#5]
1. 거래처 등록 

![image](https://user-images.githubusercontent.com/16587438/67454922-ee806600-f666-11e9-86f6-68ef0a49372c.png)

2. 매장별 제품별 수수료 
![image](https://user-images.githubusercontent.com/16587438/67454975-140d6f80-f667-11e9-9a36-909f507b0cac.png)

3. 제품별 수수료 등록
![image](https://user-images.githubusercontent.com/16587438/67455024-32736b00-f667-11e9-8c2b-7db6f7c7d8f2.png)

4. 판매 수수료 정산 
![image](https://user-images.githubusercontent.com/16587438/67455057-4f0fa300-f667-11e9-8d8a-cea434f07421.png)

관련 기능 검토 요청 드립니다.

**Comment by KwanJong-Kim-in-TU** [comment]
기간은 말씀드린거 같고 일정이 언제인지 알려주세요

**Comment by kimsang5916** [comment]
미개발 하도록 하겠습니다.
