### ISSUE TITLE
포스 화면 노출 위치 변경 

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#6]
포스 화면상 
메뉴버튼-> 후불영업관리 버튼과 모바일쿠폰 버튼의 위치 변경 
(변경후 락카현황 옆에 모바일쿠폰 위치함)

확인 완료 및 보완 되는 대로 코멘트 부탁 드립니다.

**Comment by KwanJong-Kim-in-TU** [comment]
위치변경함
천안점부터 순차 적용
