### ISSUE TITLE
통합발권 기능 수정

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#7]
포스화면상 
추가버튼-> 통합 발권, 낱장발권으로 되어있는데 낱장발권 사용하시는지 현재는 최초선택 시 낱장발권이 되어있는데 통합발권으로 변경 (각매장마다 선택지정 요망)

확인 완료 및 보완 되는 대로 코멘트 부탁 드립니다.
감사합니다.

**Comment by KwanJong-Kim-in-TU** [comment]
천안점부터 순차 적용예정
