### ISSUE TITLE
[안성팜랜드] 키오스크 쿠폰입력시 에러메시지 수정

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#8]
키오스크 쿠폰 입력시 "Invalid floating point operation" 에러메시지 뜸 

키오스크 전체 재시작 해야 확인 발권 가능 합니다. 

확인 완료 및 보완 되는 대로 코멘트 부탁 드립니다.

감사합니다.

![KakaoTalk_20191021_111612754](https://user-images.githubusercontent.com/56943833/67534896-335dd880-f70b-11e9-86fc-471bc6faaef0.jpg)

**Comment by KwanJong-Kim-in-TU** [comment]
프로그램 수정 후 배포 예정입니다
배포는 차주(11/11~11/13)에 하는걸로 하겠습니다
일정은 확인해 주세요

**Comment by mr-jang** [comment]
네 감사합니다. 
차주 11일 안성팜랜드 방문 예정입니다. 
그때 배포 진행 부탁 드립니다.
감사합니다.
