### ISSUE TITLE
[코코몽에코파크] VAN 변경 소요 작업기간 요청 

### ISSUE THREAD

**Issue by mr-jang** [kimsang5916/PLACEM#9]
코코몽 에코파크 VAN 변경 (퍼스트->나이스) 관련 하여 변경 작업 소요 기간 요청 드립니다. 

변경 예정일은 10월 31일, 11월 01일로 시점 잡고 있습니다. 

확인 및 회신 부탁드립니다.

감사합니다.

**Comment by KwanJong-Kim-in-TU** [comment]
변경된 일정 재공유 부탁드립니다
프로그램은 변경했고
테스트를 원하시면 프로그램은 별도로 전달하도록 하겠습니다
